name: four
channels:
  - conda-forge
dependencies:
  - nodejs=18.13.0
  - python=3.10.9
  - flask-socketio=5.3.2
  - requests=2.28.2
  - websocket-client=1.5.1
  - aiohttp=3.8.4
  - pip=23.0.1
  - pip:
      - simple-websocket==0.9.0

